rails-app/config/routes.rb
Rails.application.routes.draw do

  resources :healthids
  get 'static_pages/login' => 'static_pages#login', as: :login
  get 'static_pages/success' => 'static_pages#success', as: :success
  root 'static_pages#login'

end

rails-app/app/models/healthid.rb
class Healthid < ActiveRecord::Base
  mount_uploader :photo, ProfileUploader
end

rails-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails-app/app/controllers/healthids_controller.rb
require 'rjb'

class HealthidsController < ApplicationController

  def index
    @health_ids = Healthid.all
  end

  def show
    @health_id = Healthid.find_by(params[:health_id])
    @photo = photo_names[@health_id.fname]
  end

  def create
    entry = Healthids.new(params)
  end

  def health_id_params
    params.permit(fname, lname, health_id)
  end

  def photo_names
    { "Kaleb"=>"kaleb.jpeg",
      "Chantal"=>"chantal.jpeg",
      "Cal"=>"cal.jpeg",
      "Niki"=>"nikki.jpeg" }
  end
end

rails-app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def login
  end
  def success
  end
end

rails-app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-app/app/helpers/healthids_helper.rb
require 'rjb'

module HealthidsHelper
  @previous_id = '0000000000000'

  def self.get_facial_features(photo)
    Rjb::load(classpath='.:FaceSDK.jar:jna.jar', jvmargs=[])
    fsdk = Rjb::import('Luxand.FSDK')
    himage = Rjb::import('Luxand.FSDK$HImage')
    features = Rjb::import('Luxand.FSDK$FSDK_Features$ByReference')
    fsdk.ActivateLibrary("Jv9tGsCU1UeKeh/NY/7SK5VRXQJVcvv9brYdae1Cp+h1lkWK526iMLWl9f63uWW6uA65yfEP5CJGlA2XAqnBr1LJUH9Si4i0lltmVYWZ7rIZ10fHlpT9h+10en9Hw6wmAuUf51oFmhjNw2BxwN1hptZQG/6/r2W7mmd90c/fbwU=")
    fsdk.Initialize()
    fsdk.SetFaceDetectionParameters(true, true, 500)
    img = himage.new
    fsdk.LoadImageFromFile(img, photo)
    facialFeatures = features.new
    fsdk.DetectFacialFeatures(img, facialFeatures)
    facialFeatures
  end

  def self.hash_key(arr)
    x_coords = []
    y_coords = []
    max_num = 50000
    arr.features.each { |p| x_coords << p.x; y_coords << p.y }
    coords = (x_coords+y_coords).flatten
    # coords.map { |e| (Math.sin((2 * Math::PI) * (((x + 48617).to_f % max_num) / max_num ) + 1) * max_num * 1000 ).round(0) }
    coords.map! { |x| x + 48617 }
    coords.map! { |x| x.to_f }
    coords.map! { |x| x / max_num }
    coords.map! { |x| x * 2 * Math::PI }
    coords.map! { |x| Math.sin(x) }
    coords.map! { |x| x + 1 }
    coords.map! { |x| x * max_num * 1000 }
    coords.map! { |x| x.round(0) }
    coords.map! { |x| x.to_s.rjust(9, '0') }
    str = ''
    coords.each_with_index do |x, index|
      break if index >= coords.length / 2
      str << x
      str << coords[index + (coords.length / 2)]
    end
    str
  end

  def self.create_health_id
    country_code = 840
    new_id = (@previous_id.to_i + 1).to_s.rjust(13, '0')
    @previous_id = (@previous_id.to_i + 1).to_s.rjust(13, '0')
    country_code.to_s << new_id
  end
end

rails-app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

rails-app/app/views/healthids/index.html.haml
- @health_ids.each do |health_id|
  = health_id.fname
  = health_id.lname
  = health_id.health_id

rails-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripleMyMeds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navber-header">
        <a class="navbar-brand" href="#">TripleMyMeds</a>
      </div>
    </div>
  </nav>
<%= yield %>

</body>
</html>

rails-app/app/views/static_pages/login.html.haml
Hello!
%p Upload an image:
%input{type:'file', required: true}
%br
%button{class:'btn btn-success'}= link_to 'login', success_path

rails-app/app/views/static_pages/success.html.haml
.col-md-12
  .panel.panel-primary
    .panel-heading Health Id
    .col-md-4.col-md-offset-1
      = image_tag "/img/cal.jpeg"
    .col-md-6
      %label Name:
      %p Cal Al-Dhubaib
      %label Health id: 
      %p 84000016328539281